{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "crud-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ .Values.secret.connectionString | quote }}
{{- end }}
